### ISSUE TITLE
Correction required for npm install command documentation

### ISSUE THREAD

**Issue by jitendersandhu** [vladshcherbin/rollup-plugin-copy#1]
Hi @meuter ,

Thanks for adding this plugin!

There is a minor correction required in the `npm install` command given in the [installation](https://github.com/meuter/rollup-plugin-copy#installation) step in the documentation.

`npm install rollup-copy-plugin` to be corrected to `npm install rollup-plugin-copy`.

Also, I have been wondering if there is an option to copy the generated files after they are added to `dest` folder ? As a workaround, I am using [rollup-plugin-execute](https://github.com/audinue/rollup-plugin-execute) to execute the shell command to copy files.

Thanks!

**Comment by vladshcherbin** [comment]
Command is fixed in 0.3.0.

As for the second part, if you still need this, please open a new issue and I'll think how this can be done.

**Comment by jitendersandhu** [comment]
@vladshcherbin - Thanks for the quick fix and the hook suggestion! :) much appreciated!
