### ISSUE TITLE
ongenerate hook is deprecated

### ISSUE THREAD

**Issue by lluar** [vladshcherbin/rollup-plugin-copy#13]
rollup-plugin-copy plugin: The ongenerate hook used by plugin rollup-plugin-copy is deprecated. The generateBundle hook should be used instead

**Comment by CodeLionX** [comment]
I second this issue.

**Comment by vedtam** [comment]
here as well, it would be great if this could be fixed.

**Comment by spudmashmedia** [comment]
Hey guys just created a PR for this: #14 
I've tested against one of my private projects and the artefacts produce appear to be ok.
Can someone else in this community also verify?

**Comment by marverix** [comment]
Probably owner of this repo doesn't care anymore about this plugin.
Feel free to use and contribute https://github.com/marverix/rollup-plugin-copier

**Comment by vedtam** [comment]
Let us wait a little and eventually move afterwards. Thanks all for the contribution! :)

**Comment by lazarljubenovic** [comment]
Hey @meuter! Can we transfer this repo to some community group with several owners so we can bring this repo back to life? It'd be a shame to let this package go to waste, since it's the first result and has a good and self-descriptive name.

**Comment by meuter** [comment]
Hi everyone, 
Sorry for the lack of feedback, but you know... life. As you probably gathered by now, I have not been working on this project for a while now. I was not expecting that this little thing would gather so much interest. Thanks to all contributors to pick up my slack. In any case, I would gladly transfer ownership of this plugin to the community. Who is willing to take over the npm admin? Once transfer, I'll add a note in the README to redirect to the newly community maintained fork.

**Comment by spudmashmedia** [comment]
@meuter welcome back! 🙌
Are you able to merge the small patch for completeness before transferring the repo to the next custodian?

**Comment by vladshcherbin** [comment]
@meuter hey,

I can take care of `rollup-plugin-copy`. I'm kinda tired with creating issues in different rollup copy plugins and almost all of them have at least one. So, between creating my own one vs taking care of an existing one, I'd choose the second option.

There is no need to fork this repo or deprecate, repo [can be transferred](https://help.github.com/en/articles/transferring-a-repository) to a different user on github, same for npm [package owner](https://docs.npmjs.com/cli/owner). I'll make sure you'll be mentioned as a co-author as all I want is to have a single reliable and well-maintained copy plugin.

I already have some rollup plugins: e.g. [delete](https://github.com/vladshcherbin/rollup-plugin-delete), [generate-package-json](https://github.com/vladshcherbin/rollup-plugin-generate-package-json) which I maintain so your plugin will be in good hands.

If you agree, transfer repo and npm owner and I'll take care of this repo.

Thank you 😉

**Comment by vladshcherbin** [comment]
Okay, I'm the new maintainer now. 🍾 

This is fixed in 0.3.0, which is a small release just for this issue. Other features and changes will be published in next major/minor versions.

Thank you 😉

**Comment by spudmashmedia** [comment]
Finally got there 🙌
