### ISSUE TITLE
Copy just one time

### ISSUE THREAD

**Issue by frederikhors** [vladshcherbin/rollup-plugin-copy#20]
It would be amazing to copy just one time.

Example: I need to copy just the first time my `npm run dev` start all the files from `public` folder to `dist`.

Every time I change a `.js` file I don't need to copy again the files from public to dist.

Is there a way?

**Comment by lazarljubenovic** [comment]
I wonder if it's possible for the plugin to detect this behavior automatically, i.e. if the file hasn't changed, then there's no need to copy it again :thinking:

**Comment by frederikhors** [comment]
But anyway there is too much work that I can avoid with an option.

**Comment by vladshcherbin** [comment]
I've actually added this feature as an option this week, it will be in the next version, released in a few days.

@lazarljubenovic For now it's an option. Automatically may work, but it overlaps with watch file functionality which I plan to add later (https://github.com/vladshcherbin/rollup-plugin-copy/issues/5) and rollup watch mode. I'll think if there is a way for both of them work together without issues.

**Comment by vladshcherbin** [comment]
Released in 3.0.0 🎉
