### ISSUE TITLE
Copying entire directory excluding file extension

### ISSUE THREAD

**Issue by riccardonuzz** [vladshcherbin/rollup-plugin-copy#24]
Hi, I'm trying to copy the /src/profiles folder into /dist and it works very well, but wat I'm trying to do is excluding all the .tsx files inside the /src/ subfolder. Is it possible to do something like this with this plugin?

I tried with

`copy({
   targets: [{
      src: ['src/profiles', '!**/*.tsx'],
      dest: 'dist'
   }]
})`

as stated in the readme.md but nothing seems to work.

**Comment by vladshcherbin** [comment]
@riccardonuzz hey, I've checked this config:

```js
copy({
  targets: [
    { src: ['assets/*', '!**/*.tsx'], dest: 'dist/assets' }
  ]
})
```

It works for me. 🤔

I can upload my test repo to see if it works for you or you can show yours? also, what OS are you using, maybe it's related?

**Comment by riccardonuzz** [comment]
Ok, I just updated the previous message. So this is what I'm trying to achieve:
- I need to copy the src/profiles folder keeping the folder structure. (This is why I'm not using src/*, cause it copies all files in the root of selected destination).
- During the copy process I need to exclude .tsx files.

**Comment by vladshcherbin** [comment]
@riccardonuzz okay, so this is your code:

```js
copy({ targets: [{ src: ['src/profiles', '!**/*.tsx'], dest: 'dist' }] })
```

`src/profiles` will select folder, `!**/*.tsx` will exclude files. What you need is to select files and exclude files. Try this one instead:

```js
copy({ targets: [{ src: ['src/profiles/*', '!**/*.tsx'], dest: 'dist/profiles' }] })
```

You can change `dist/profiles` to any folder you want files copy to.

**Comment by vladshcherbin** [comment]
Hey, @riccardonuzz 

Any chance you can test the solution so I can close the issue or give other suggestions if it doesn't help?

**Comment by vladshcherbin** [comment]
Closing due to no response. Feel free to comment if the solution, provided above, doesn't work
