### ISSUE TITLE
Folder Hierarchy not preserved

### ISSUE THREAD

**Issue by sebdoucet** [vladshcherbin/rollup-plugin-copy#26]
Hi,

I'm using a glob filter like this: `packages/my-package/src/**/*.css` and I was expecting that the folder hierarchy will be preserved. I'm using it to bundle my css using imports.

Cheers.

**Comment by vladshcherbin** [comment]
@sebdoucet hey 👋 

Yes, this is the correct default behavior. I believe you can experiment with [expandDirectories](https://github.com/sindresorhus/globby#expanddirectories) option to preserve folder structure 🤔

**Comment by sebdoucet** [comment]
Ok, my bad, I havent read the readme properly... Extra property forwarded to sub lib...

I'm going to try that tomorrow, ty!
