### ISSUE TITLE
Don't overwrite existing file

### ISSUE THREAD

**Issue by jbergstroem** [vladshcherbin/rollup-plugin-copy#33]
I currently generate a lot of google functions from typescript via rollup. Some have exceptions in terms of how they are deployed which makes me bundle an env file; but I would like to only do so if the env file doesn't already exist. 

I'd like to make the case for a clause that copies file only if the destination doesn't exist. If there's interest I can have a look at writing it. Thoughts?

**Comment by vladshcherbin** [comment]
@jbergstroem hey, it's already actually possible to not overwrite existing file:

```js
copy({
  targets: [{ src: 'src/index.html', dest: 'dist/public' }],
  overwrite: false
})
```

Is this what you need?

**Comment by jbergstroem** [comment]
> Is this what you need?

That's exactly it. Guessing its missing from docs then?

**Comment by vladshcherbin** [comment]
@jbergstroem it's an option from [fs-extra copy function](https://github.com/jprichardson/node-fs-extra/blob/7.0.0/docs/copy.md), which is mentioned after [copyOnce](https://github.com/vladshcherbin/rollup-plugin-copy#copyonce) option in the docs of this package:

> All other options are passed to packages, used inside:
>
> - globby
> - fs-extra copy function

Not sure if all options from globby and fs-extra packages need to be mentioned, there are a lot of them and they'll need to be updated as this packages update.

If you have a better idea how to mention this, I'm open to any suggestions :)

**Comment by jbergstroem** [comment]
> If you have a better idea how to mention this, I'm open to any suggestions :)

After you've explained to me, I don't. Perhaps just mention it as an example? Happy to make a PR to add to README.md if you feel it's da way.

**Comment by vladshcherbin** [comment]
@jbergstroem sure, go for it :)

**Comment by vladshcherbin** [comment]
Closing due to being resolved
