### ISSUE TITLE
Feature request: Add "ignore" option for inverted use

### ISSUE THREAD

**Issue by moqmar** [vladshcherbin/rollup-plugin-copy#39]
If I know that I'm using Rollup to convert `.vue`, `.js` and `.css` files, I'd like to be able to copy everything else to the output dir:

```js
copy({
  targets: [
    { src: 'src/**', dest: 'public', ignore: ['*.vue', '*.js', '*.css'] }
  ]
})
```

**Comment by abdonrd** [comment]
Any news here? Thanks!

**Comment by moqmar** [comment]
I figured out, it actually already works through [globby](https://github.com/sindresorhus/globby), the syntax is just a bit weird:

```javascript
copy({
    targets: [
        { src: ["src/**", "!**/*.{vue,js,css}"], dest: "dist" },
    ]
})
```

**Comment by abdonrd** [comment]
@moqmar I just tried with this and doesn't work for me with the folders:

```javascript
copy({
  targets: [
    {
      src: [
        `public/**/*`,
        `!public/node_modules/**/*`,
        `!public/patches/**/*`,
        `!public/src/**/*`,
        `!public/src-js/**/*`,
        `!public/package-lock.json`,
        `!public/package.json`
      ],
      dest: DIST_PATH
    }
  ],
  flatten: false
})
```

This four selected folders shouldn't be there:

<img width="294" alt="Screenshot 2020-04-25 at 19 57 28" src="https://user-images.githubusercontent.com/1007051/80286985-0bd5e000-872f-11ea-90cc-a6e0c2ffc014.png">

**Comment by moqmar** [comment]
I think for folders you can just use `!public/node_modules/`? I haven't tried it though...

**Comment by abdonrd** [comment]
Thanks @moqmar !

Doesn't work:
- `!public/node_modules/**/*`
- `!public/node_modules/`

Works!
- `!public/node_modules`
