### ISSUE TITLE
Move `@types/*` in dependencies.

### ISSUE THREAD

**Issue by solominsn** [vladshcherbin/rollup-plugin-copy#65]
I'm using this plugin to build a library for the browser. The library uses typescript checking, so it loads type definitions from

**Comment by solominsn** [comment]
I've decided to make a fork and fix it.

**Comment by solominsn** [comment]
I've found a way to avoid this package usage.

But to fix the source problem with invalid '@type/node' dependency is enough to move `@types/fs-extra` package to `devDependencies` section and update `globby` to `11.0.4` (10.x version had the same problem with `@types/node` dependency).

**Comment by vladshcherbin** [comment]
Hi 👋 There are no `@types/*` packages in `dependencies` or `devDependencies`, it's typescript free. Maybe the error is from `globby` package which you've mentioned, I'll update it and hopefully it will be fixed.

**Comment by solominsn** [comment]
`package.json` in master contains `@types/fs-extra`, but it seems to be required for d.ts file to work properly.
