### ISSUE TITLE
Change Async to Sync, and add option when do job

### ISSUE THREAD

**Issue by justgook** [vladshcherbin/rollup-plugin-copy#8]
```
    ongenerate: function (object) {
      for (let key in options) {
        if (key == "verbose") continue;
        const src = key;
        const dest = options[key];
        try {
          fse.copySync(src, dest)
          if (verbose) success(name, src, dest);
        } catch (err) {
          fatal(name, src, dest, err);
        }
      }
    }```

and second - make possible execute that after files is generated, or inplace.. 
it is usefull when You would like first copy some files, and then apply some (text replacement on those files)

**Comment by marverix** [comment]
I don't know if it will help you but in  https://github.com/marverix/rollup-plugin-copier you have option `hookOn` available.

**Comment by vladshcherbin** [comment]
In 1.0.0 files are correctly copied in sequential async `generateBundle` hook. Other plugins will have access to files when placed after `copy` plugin so text replacement or other transformations can be done there.

Try the new version to see if it fits your needs 😉

**Comment by riccardonuzz** [comment]
I'm using rollup-plugin-delete and placing it after copy plugin but I'm unable to delete files in dist folder. It looks like del plugin runs always before copy plugin.

**Comment by vladshcherbin** [comment]
@riccardonuzz yes, `delete` plugin uses `buildStart` hook and `copy` uses `buildEnd` hook so no matter what order you place plugins, delete will run first, then copy.

There is an option [hook](https://github.com/vladshcherbin/rollup-plugin-copy#hook) where you can set what hook to use, you can try to set it to `options` hook which is executed before `buildStart` so delete hook will be executed after copy. (don't try to set it to `buildStart` and rely on plugins order, this hook runs plugins in parallel and it's a small limitation of current rollup plugin system)

I'll add a hook option to delete plugin too, so you can change it for this case:

- copy - `buildStart` hook
- delete - `buildEnd` hook

**Comment by vladshcherbin** [comment]
@riccardonuzz update `rollup-plugin-delete` to 1.1.0 and you can solve it this way:

```js
plugins: [
  copy({ ..., hook: 'buildStart' }),
  del({ ..., hook: 'buildEnd' })
]
```

**Comment by riccardonuzz** [comment]
Problem solved, thank you! :)
